title: Lability tutorial
theme: jekyll-theme-architect
repository: mrled/lability-tutorial
markdown: kramdown
baseurl: /lability-tutorial
author:
  name: Micah R Ledbetter
  url: https://me.micahrl.com
collections_dir: collections
collections:
  hypervconcepts:
    output: true
    permalink: /backmatter/concepts/hyperv/:name
  powershellconcepts:
    output: true
    permalink: /backmatter/concepts/powershell/:name
  labilityconcepts:
    output: true
    permalink: /backmatter/concepts/lability/:name
defaults:
  - scope:
      type: hypervconcepts
    values:
      layout: default
  - scope:
      type: powershellconcepts
    values:
      layout: default
  - scope:
      type: labilityconcepts
    values:
      layout: default
