title: Lability tutorial
theme: jekyll-theme-architect
repository: mrled/lability-tutorial
markdown: kramdown
baseurl: /lability-tutorial
author:
  name: Micah R Ledbetter
  url: https://me.micahrl.com
